### PR TITLE
log payload size

### PR DESCRIPTION
**Pull request by anupvarghese**
Log size of JSON stringified payload. Is this good enough?

### CODE REVIEW

**Comment by danielmoi** [comment]
http://ingest.tips/2015/01/21/handling-large-messages-kafka/
1. The best way to send large messages is not to send them at all. If shared storage is available (NAS, HDFS, S3), placing large files on the shared storage and using Kafka just to send a message about the file’s location is a much better use of Kafka.
2. The second best way to send large messages is to slice and dice them. Use the producing client to split the message into small 10K portions, use partition key to make sure all the portions will be sent to the same Kafka partition (so the order will be preserved) and have the consuming client sew them back up into a large message.
3. Kafka producer can be used to compress messages. If the original message is XML, there’s a good chance that the compressed message will not be very large at all. Use compression.codec and compressed.topics configuration parameters in the producer to enable compression. GZip and Snappy are both supported.

**Comment by davidbanham** [comment]
Oooooh compression is an interesting one. Good post, @danielmoi.

I think I recall seeing that we are using compression from looking at the configs. That's fine, it just means that the sizes we see logged out from this PR may not _actually_ be the sizes of the messages that get pushed.

We'll be logging the size _before_ compression whereas the size we care about is _after_ compression.

To be clear, I think we should still merge and deploy this code in order to hit our 12:30 window. I just want to point this out so that we have it in mind when we're evaluating this logged data. It'll still be useful information, we just need to look at it in relative rather than absolute terms.

**Comment by davidbanham** [comment]
LGTM

**Comment by danielmoi** [comment]
Yes, I agree, LGTM
There's a wealth of stuff to be mined.
Good start! 👍

**Pull request merged**
